/* Generated by wayland-scanner 1.23.0 */

/*
 * SPDX-FileCopyrightText: 2023 Vlad Zahorodnii
 *
 * SPDX-License-Identifier: MIT-CMU
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface kde_auto_hide_screen_edge_v1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *kde_screen_edge_v1_types[] = {
	&kde_auto_hide_screen_edge_v1_interface,
	NULL,
	&wl_surface_interface,
};

static const struct wl_message kde_screen_edge_manager_v1_requests[] = {
	{ "destroy", "", kde_screen_edge_v1_types + 0 },
	{ "get_auto_hide_screen_edge", "nuo", kde_screen_edge_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kde_screen_edge_manager_v1_interface = {
	"kde_screen_edge_manager_v1", 1,
	2, kde_screen_edge_manager_v1_requests,
	0, NULL,
};

static const struct wl_message kde_auto_hide_screen_edge_v1_requests[] = {
	{ "destroy", "", kde_screen_edge_v1_types + 0 },
	{ "deactivate", "", kde_screen_edge_v1_types + 0 },
	{ "activate", "", kde_screen_edge_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kde_auto_hide_screen_edge_v1_interface = {
	"kde_auto_hide_screen_edge_v1", 1,
	3, kde_auto_hide_screen_edge_v1_requests,
	0, NULL,
};

